services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:2.0.3
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    env_file:
      - ./nacos-hostname.env
    environment:
      NACOS_APPLICATION_PORT: 8848
    restart: always
  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:2.0.3
    container_name: nacos2
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "7948:7848"
      - "8948:8848"
      - "9948:9848"
      - "9949:9849"
    env_file:
      - ./nacos-hostname.env
    environment:
      NACOS_APPLICATION_PORT: 8948
    restart: always